ui <- fluidPage(theme = shinytheme("superhero"),
          tags$head(
            tags$link(rel = "stylesheet", type = "text/css", href = "mystyle.css")
          ),
          useShinyjs(),
          useShinyalert(),
          useShinyFeedback(), 
          h2('Time Series Upload'),
          inputPanel(
            fileInput("i_file", "Upload your CSV file"),
            # br(),
            selectInput('variable','Select Series',choices = NULL),
            # br(),
            # uiOutput('observations_to_account'),
            sliderInput("observations", 
                        label = ("Obseravations to load"), 
                        min = 10,
                        max = 100,
                        value = c(10, 100)),
            # br(),
            awesomeRadio(inputId = "frequency_known", 
                         label = "Is frequency known? ", 
                         choices = c("Yes" = 1, 
                                     "No" = 2), 
                         selected = 2),
            # br(),
            uiOutput('frequency_type'),
           
            br()),
          br(),
          conditionalPanel(condition = "(input.variable.length > 0)",
                           actionButton('submit', "Submit")),
          br(),
          hr(),
          hidden(div(align = 'left',
                     id = 'seriesdiv',
                     highchartOutput('series'))), 
          br(),
          hr(),
          h2('Evaluation Scheme'),
          awesomeCheckboxGroup(inputId = "Algorithm", 
                               label = h3("Select a family of algorithms to optimize, fit and evaluate"), 
                               choices = c("DRIFT : ARIMA(0,1,0) model with an optional random walk drift model" = "DRIFT",
                                           "Seasonal NAIVE : ARIMA(0,0,0)(0,1,0)m model where m is the seasonal period" = "NAIVE",
                                           "(S)ARIMA : Estimate the best (S)ARIMA model according the Information Criterion selected" = 'ARIMA',
                                           "ETS : Fit Exponential smoothing state space model"="ETS", 
                                           "TBATS : Exponential smoothing state space model with Box-Cox transformation, ARMA errors, Trend and Seasonal components"='TBATS',
                                           "PROPHET : Fit a Prophet forecaster"='PROPHET', 
                                           'THETA : Choose between 5 variation of the theta model to fit and evaluate' = 'THETA',
                                           'NNETAR : Feed-forward neural networks with a single hidden layer and lagged inputs'='NNETAR',
                                           'CES : Estimate the best Complex Exponential Smoothing model according the Information Criterion selected'='CES'),
                               selected = NULL, 
                               inline = F,
                               width = '2000px'),
          uiOutput('ensemble_params'),
          br(),
          uiOutput('holdout_slider'),
          br(),
          h3('Algorithms Settings'),
          tabsetPanel(type="tabs",
                      #build forecasting panels
                      tabPanel("DRIFT", icon = icon("line-chart"), h4("NAIVE"),
                               br(),
                               inputPanel(
                                 checkboxInput('drift', 'Apply drift model?', value = T),
                                 selectInput(inputId = 'drift_lambda',
                                             label = 'Box-Cox transformation parameter',
                                             choices = c("No transformation" = 'NULL', "Find optimal" = 'auto'),
                                             selected = "NULL" )
                               ), 
                               value=1),
                      
                      tabPanel("NAIVE", icon = icon("line-chart"), h4("NAIVE"),
                               br(),
                               inputPanel(
                                 selectInput(inputId = 'naive_lambda',
                                             label = 'Box-Cox transformation parameter',
                                             choices = c("No transformation" = 'NULL', "Find optimal" = 'auto'),
                                             selected = "NULL" )
                               ), 
                               value=2),
                      tabPanel("(S)ARIMA", icon = icon("line-chart"), h4("(S)ARIMA"),
                               br(),
                               inputPanel(
                                 numericInput('max.p','Maximum value of AR terms',value = 5),
                                 numericInput('max.q','Maximum value of MA terms',value = 5),
                                 numericInput('max.P','Maximum value of seasonal AR terms',value = 2),
                                 numericInput('max.Q','Maximum value of seasonal MA terms',value = 2),
                                 numericInput('max.order','Maximum value of p+q+P+Q if model selection is not stepwise',value = 5),
                                 numericInput('max.d','Maximum value of difference order',value = 2),
                                 numericInput('max.D','Maximum value of seasonal difference order',value = 1),
                                 selectInput('arima_ic','Information criterion to evaluate best (S)ARIMA', choices = c("aicc", "aic", "bic"), selected = "aic"),
                                 selectInput('arima_lambda','Box-Cox transformation parameter', choices = c("No transformation" = 'NULL', "Find optimal" = 'auto'), selected = "NULL"),
                                 checkboxInput('allowdrift','Consider models with drift terms',value = T), 
                                 checkboxInput('allowmean','Consider models with a non-zero mean',value = T),
                                 checkboxInput('seasonal','Include seasonal models in search?',value = T),
                                 checkboxInput('stationary','Restrict search to stationary models?',value = T),
                                 checkboxInput('approximation','Approximate estimation? (faster but less accurate)',value = T),
                                 checkboxInput('stepwise','Stepwise selection? (faster but less accurate)',value = T)
                               ), 
                               value=3),
                      tabPanel("ETS", icon = icon("line-chart"), h4("ETS"), 
                               br(), 
                               inputPanel(
                                 
                                 selectInput(inputId = 'errortype',
                                             label = 'Error Type',
                                             choices = c('Additive'="A", 'multiplicative'="M", 'Automatically selected'= "Z"),
                                             selected = 'Z'),
                                 selectInput(inputId = 'trendtype',
                                             label = 'Trend Type',
                                             choices = c('None'="N",'Additive'="A", 'multiplicative'="M", 'Automatically selected'= "Z"),
                                             selected = 'Z'),
                                 selectInput(inputId = 'seasontype',
                                             label =   'Season Type',
                                             choices = c('None'="N",'Additive'="A", 'multiplicative'="M", 'Automatically selected'= "Z"),
                                             selected = 'Z'),
                                 selectInput('ets_lambda','Box-Cox transformation parameter', 
                                             choices =  c("No transformation" = 'NULL', "Find optimal" = 'auto'), 
                                             selected = "NULL"),
                                 selectInput('opt.crit','Optimization criterion', 
                                             choices = c("Mean Square Error" = 'mse', 
                                                         "Average MSE over first nmse forecast horizons" = 'amse',
                                                         "Standard deviation of residuals" = 'sigma',
                                                         "Mean of absolute residuals" = 'mae',
                                                         "Log-likelihood" = 'lik'), selected = "lik"),
                                 selectInput('ets_ic','Information criterion to evaluate best ETS model', choices = c("aicc", "aic", "bic"), selected = "aic"),
                                 checkboxInput('allow.multiplicative.trend', 'Always include multiplicative trends?',value = T)
                               ),
                               value=4),
                      tabPanel("TBATS", icon = icon("line-chart"), h4("TBATS"), 
                               br(), 
                               inputPanel(
                                 checkboxInput('use.arma.errors','Use ARMA errors',value = T)),
                               value=5),
                      tabPanel("PROPHET", icon = icon("line-chart"), h4("PROPHET"), 
                               br(), 
                               inputPanel(
                                 selectInput(label = 'Growth', inputId = 'growth', choices = c( 'linear', 'flat'),selected = "linear"),
                                 selectInput(label = 'Seasonality mode', inputId = 'seasonality.mode', choices = c('additive', 'multiplicative'),selected = "additive"),
                                 selectInput(label = 'Yearly seasonality', inputId = 'yearly.seasonality', choices = c('auto', TRUE, FALSE),selected = "auto"),
                                 selectInput(label = 'Weekly seasonality', inputId = 'weekly.seasonality', choices = c('auto', TRUE, FALSE),selected = "auto"),
                                 selectInput(label = 'Daily seasonality', inputId = 'daily.seasonality', choices = c('auto', TRUE, FALSE),selected = "auto"),
                                 numericInput(inputId = 'n.changepoints', label = 'Maximum number of trend changepoints', value = 25, min = 0, max = 100),
                                 numericInput(inputId = 'changepoint.range', label = 'Changepoint range', value = 0.8, min = 0.1, max = 1)),
                               value=6),
                      tabPanel("THETA", icon = icon("line-chart"), h4("THETA"), 
                               br(), 
                               inputPanel(
                                 selectInput(inputId = 'theta_model',
                                             label = 'Select model',
                                             choices = c('Dynamic Optimised Theta Model', 
                                                         'Dynamic Standard Theta Model', 
                                                         'Optimised Theta Model',
                                                         'Standard Theta Model',
                                                         'Standard Theta Method (STheta)'),
                                             selected = 'Dynamic Optimised Theta Model'),
                                 selectInput(inputId = 's', 
                                             label = 'Seasonality', 
                                             choices = c('Multiplicative' = 'T', 'Additive'='additive', 'Unknown'='NULL'),
                                             selected = 'NULL'),
                                 conditionalPanel(condition = "input.theta_model != 'Standard Theta Method (STheta)'",
                                                  selectInput(label = 'Optimization Method', inputId = 'opt.method', choices = c('Nelder-Mead', 'L-BFGS-B', 'SANN'),selected = 'Nelder-Mead'))
                               ),
                               value=7),
                      tabPanel("NNETAR", icon = icon("line-chart"), h4("NNETAR"), 
                               br(), 
                               inputPanel(
                                 numericInput(inputId = 'number_of_seasonal_lags',
                                              label = 'Number of seasonal lags',
                                              value = 1,
                                              max = 30,
                                              min = 1,
                                              step = 1),
                                 numericInput(inputId = 'repeats',
                                              label = 'Repeats',
                                              value = 20,
                                              max = 100,
                                              min = 1,
                                              step = 1),
                                 selectInput(inputId = 'nnetar_lambda', 
                                             label = 'Lamda transformation', 
                                             choices = c('Auto' = 'auto',  'No transformation'='NULL'),
                                             selected = 'auto'),
                                 checkboxInput(inputId = 'scale.inputs','Scale inputs',value = F)
                               ),
                               value=8),
                      tabPanel("CES", icon = icon("line-chart"), h4("NNETAR"), 
                               br(), 
                               inputPanel(
                                 selectInput(inputId = 'CES_seasonality', 
                                             label = 'Type of seasonality models', 
                                             choices = c('No seasonality' = 'none', 
                                                         'Simple seasonality'='simple',
                                                         'Additive seasonality'='partial',
                                                         'Full seasonality with complex seasonal components'='full'),
                                             multiple = T,
                                             selected = c("none", "simple", "full")),
                                 selectInput(inputId = 'ces_ic',
                                             label = 'Information criterion to evaluate best CES model',
                                             choices = c("AICc", "AIC", "BIC","BICc"),
                                             multiple = T,
                                             selected = c("AICc", "AIC", "BIC","BICc")),
                                 selectInput(inputId = 'initial_state',
                                             label = 'How to produce initial states?', 
                                             choices = c("Find optimal"="optimal", "With backtesting"="backcasting"), 
                                             multiple = T,
                                             selected = c("backcasting", "optimal")),
                                 selectInput(inputId = 'loss',
                                             label = 'What loss function to use in optimization?', 
                                             choices = c("Likelihood "="likelihood", 
                                                         "MSE", 
                                                         "MAE", 
                                                         'Half Absolute Momen' = 'HAM',
                                                         "Geometric Trace Mean Squared Error" = 'GTMSE'), 
                                             multiple = T,
                                             selected = c("likelihood", "MSE", "MAE", "HAM", "MSEh", "TMSE","GTMSE", "MSCE")),
                                 selectInput(inputId = 'interval',
                                             label = 'What type of prediction interval to construct?', 
                                             choices = c("none", "parametric", "likelihood", "semiparametric","nonparametric"), 
                                             selected =  c("none", "parametric", "likelihood", "semiparametric","nonparametric"))
                               ),
                               value=9),
               
                      id = "timeSeriesTabs"),
          br(),
          br(),
          actionButton('evaluate','Evaluate'),
          br(),
          br(),
          dataTableOutput('results'),
          uiOutput('dt_row_selector'),
          br(),
          shiny::uiOutput("dynamic_tabs"),
          br(),
          br(),
          uiOutput('forecast_widget_container'),
          uiOutput('forecast_tabs_container')
)